ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.mohsin.ApplicationKt.module

postgres:
  url: "jdbc:postgresql://localhost:5432/eventdb"
  user: "postgres"
  password: "postgres"

